spring:
  application:
    name: employee-api
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8111
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-binding-errors: never

logging:
  level:
    root: DEBUG


